# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('display_picture', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('CodeChef_username', models.CharField(max_length=50)),
                ('CodeForces_username', models.CharField(max_length=50)),
                ('HackerRank_username', models.CharField(max_length=50)),
                ('HackerEarth_username', models.CharField(max_length=50)),
                ('InterviewBit_username', models.CharField(max_length=50)),
                ('LeetCode_username', models.CharField(max_length=50)),
                ('SPOJ_username', models.CharField(max_length=50)),
                ('GitHub_username', models.CharField(max_length=50)),
                ('BitBucket_username', models.CharField(max_length=50)),
            ],
        ),
    ]
