# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=250)),
                ('best_known_as', models.CharField(max_length=250)),
                ('twitter', models.URLField(blank=True, default='', null=True)),
                ('facebook', models.URLField(blank=True, default='', null=True)),
                ('linkedin', models.URLField(blank=True, default='', null=True)),
                ('website', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('display_picture', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('CodeChef_username', models.CharField(blank=True, max_length=50, null=True)),
                ('CodeChef_problem', models.IntegerField(default=0)),
                ('CodeChef_rating', models.CharField(default='NA', max_length=50)),
                ('CodeForces_username', models.CharField(blank=True, max_length=50, null=True)),
                ('CodeForces_contest', models.IntegerField(default=0)),
                ('CodeForces_rating', models.CharField(default='NA', max_length=50)),
                ('HackerRank_username', models.CharField(blank=True, max_length=50, null=True)),
                ('HackerRank_problem', models.IntegerField(default=0)),
                ('HackerRank_rating', models.CharField(default='NA', max_length=50)),
                ('HackerEarth_username', models.CharField(blank=True, max_length=50, null=True)),
                ('HackerEarth_problem', models.IntegerField(default=0)),
                ('HackerEarth_rating', models.CharField(default='NA', max_length=50)),
                ('SPOJ_username', models.CharField(blank=True, max_length=50, null=True)),
                ('SPOJ_problem', models.IntegerField(default=0)),
                ('SPOJ_rating', models.CharField(default='NA', max_length=50)),
                ('GitHub_username', models.CharField(blank=True, max_length=50, null=True)),
                ('GitHub_repo', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(blank=True, default=0, null=True)),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_view', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=250)),
                ('repo_name', models.CharField(default='', max_length=250)),
                ('repo_description', models.CharField(default='', max_length=250)),
                ('repo_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=250)),
                ('skill1', models.CharField(blank=True, max_length=250, null=True)),
                ('percent1', models.IntegerField(blank=True, null=True)),
                ('skill2', models.CharField(blank=True, max_length=250, null=True)),
                ('percent2', models.IntegerField(blank=True, null=True)),
                ('skill3', models.CharField(blank=True, max_length=250, null=True)),
                ('percent3', models.IntegerField(blank=True, null=True)),
                ('skill4', models.CharField(blank=True, max_length=250, null=True)),
                ('percent4', models.IntegerField(blank=True, null=True)),
                ('skill5', models.CharField(blank=True, max_length=250, null=True)),
                ('percent5', models.IntegerField(blank=True, null=True)),
                ('skill6', models.CharField(blank=True, max_length=250, null=True)),
                ('percent6', models.IntegerField(blank=True, null=True)),
                ('skill7', models.CharField(blank=True, max_length=250, null=True)),
                ('percent7', models.IntegerField(blank=True, null=True)),
                ('skill8', models.CharField(blank=True, max_length=250, null=True)),
                ('percent8', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
