# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='user',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
