# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='BitBucket_username',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='InterviewBit_username',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='LeetCode_username',
        ),
        migrations.AddField(
            model_name='hacker',
            name='problems_solved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hacker',
            name='ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='CodeChef_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='CodeForces_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='GitHub_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='HackerEarth_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='HackerRank_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='SPOJ_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='display_picture',
            field=models.ImageField(height_field='height_field', upload_to='', width_field='width_field'),
        ),
    ]
