# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20171023_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='CodeChef_problem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hacker',
            name='CodeChef_rating',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='hacker',
            name='CodeForces_contest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hacker',
            name='CodeForces_rating',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='hacker',
            name='HackerEarth_problem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hacker',
            name='HackerEarth_rating',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='hacker',
            name='HackerRank_problem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hacker',
            name='HackerRank_rating',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='hacker',
            name='SPOJ_problem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hacker',
            name='SPOJ_rating',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
