# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20171016_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='problems_solved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
