# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20171023_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='full_name',
            field=models.CharField(default='Vishal Agrawal', max_length=150),
        ),
    ]
