# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_hacker_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='profile_view',
            field=models.IntegerField(default=0),
        ),
    ]
