# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20171016_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='problems_solved',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
